APP_ID=alfred
NAME=Alfred
CATEGORY=system
DESCRIPTION=Lanzador de aplicaciones y automatización de productividad
HOMEPAGE=https://www.alfredapp.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=alfred
PACKAGE_TYPE=cask
ARCHITECTURE=universal
