APP_ID=node
NAME=Node.js
CATEGORY=development
DESCRIPTION=Entorno de ejecución JavaScript
HOMEPAGE=https://nodejs.org/
LICENSE=MIT
INSTALL_METHOD=brew
PACKAGE_NAME=node
PACKAGE_TYPE=formula
ARCHITECTURE=universal
RELATED=docker visual-studio-code pnpm
