APP_ID=proton-vpn
NAME=Proton VPN
CATEGORY=security
DESCRIPTION=VPN de Proton con servidores sin registro de actividad
HOMEPAGE=https://protonvpn.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=protonvpn
PACKAGE_TYPE=cask
ARCHITECTURE=universal
ALTERNATIVES=Mullvad VPN, Tunnelblick
