APP_ID=macs-fan-control
NAME=Macs Fan Control
CATEGORY=system
DESCRIPTION=Control manual de ventiladores y monitoreo térmico
HOMEPAGE=https://crystalidea.com/macs-fan-control
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=macs-fan-control
PACKAGE_TYPE=cask
ARCHITECTURE=universal
HW_RECOMMEND=macbook_pro mac_mini mac_studio imac
