APP_ID=zoom
NAME=Zoom
CATEGORY=communication
DESCRIPTION=Videoconferencias y reuniones remotas
HOMEPAGE=https://www.zoom.us/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=zoom
PACKAGE_TYPE=cask
ARCHITECTURE=universal
