APP_ID=onedrive
NAME=OneDrive
CATEGORY=productivity
DESCRIPTION=Almacenamiento y sincronización en la nube de Microsoft
HOMEPAGE=https://www.microsoft.com/en-us/microsoft-365/onedrive/online-cloud-storage
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=onedrive
PACKAGE_TYPE=cask
ARCHITECTURE=universal
