APP_ID=grandperspective
NAME=GrandPerspective
CATEGORY=system
DESCRIPTION=Visualiza gráficamente el uso de espacio en disco
HOMEPAGE=https://grandperspectiv.sourceforge.net/
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=grandperspective
PACKAGE_TYPE=cask
ARCHITECTURE=universal
NOTES=Se prefirió sobre OmniDiskSweeper, que resuelve el mismo problema, para evitar duplicidad
