APP_ID=plantuml
NAME=PlantUML
CATEGORY=development
DESCRIPTION=Generación de diagramas UML a partir de texto plano
HOMEPAGE=https://plantuml.com/
LICENSE=GPL-3.0-or-later
INSTALL_METHOD=brew
PACKAGE_NAME=plantuml
PACKAGE_TYPE=formula
ARCHITECTURE=universal
