APP_ID=zen
NAME=Zen
CATEGORY=browsers
DESCRIPTION=Navegador basado en Firefox con espacios de trabajo y pestañas verticales
HOMEPAGE=https://zen-browser.app/
LICENSE=MPL-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=zen-browser
PACKAGE_TYPE=cask
ARCHITECTURE=universal
