APP_ID=lulu
NAME=LuLu
CATEGORY=security
DESCRIPTION=Firewall de salida open-source y gratuito
HOMEPAGE=https://objective-see.org/products/lulu.html
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=lulu
PACKAGE_TYPE=cask
ARCHITECTURE=universal
ALTERNATIVES=Little Snitch
