APP_ID=wireshark
NAME=Wireshark
CATEGORY=networking
DESCRIPTION=Analizador de protocolos de red
HOMEPAGE=https://www.wireshark.org/
LICENSE=GPL-2.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=wireshark-app
PACKAGE_TYPE=cask
ARCHITECTURE=universal
