APP_ID=dbeaver
NAME=DBeaver Community
CATEGORY=development
DESCRIPTION=Cliente universal de bases de datos con interfaz gráfica
HOMEPAGE=https://dbeaver.io/
LICENSE=Apache-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=dbeaver-community
PACKAGE_TYPE=cask
ARCHITECTURE=universal
