APP_ID=pearcleaner
NAME=Pearcleaner
CATEGORY=system
DESCRIPTION=Desinstalador de aplicaciones open-source con búsqueda de residuos
HOMEPAGE=https://itsalin.com/appInfo/?id=pearcleaner
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=pearcleaner
PACKAGE_TYPE=cask
ARCHITECTURE=universal
ALTERNATIVES=AppCleaner
