APP_ID=vlc
NAME=VLC media player
CATEGORY=media
DESCRIPTION=Reproductor multimedia universal, compatible con prácticamente cualquier formato
HOMEPAGE=https://www.videolan.org/vlc/
LICENSE=GPL-2.0-or-later
INSTALL_METHOD=cask
PACKAGE_NAME=vlc
PACKAGE_TYPE=cask
ARCHITECTURE=universal
ALTERNATIVES=IINA
