APP_ID=cyberduck
NAME=Cyberduck
CATEGORY=networking
DESCRIPTION=Cliente FTP, SFTP y almacenamiento en la nube
HOMEPAGE=https://cyberduck.io/
LICENSE=GPL-3.0-or-later
INSTALL_METHOD=cask
PACKAGE_NAME=cyberduck
PACKAGE_TYPE=cask
ARCHITECTURE=universal
