APP_ID=discord
NAME=Discord
CATEGORY=communication
DESCRIPTION=Comunicación por voz, video y texto para comunidades
HOMEPAGE=https://discord.com/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=discord
PACKAGE_TYPE=cask
ARCHITECTURE=universal
