APP_ID=nmap
NAME=Nmap
CATEGORY=networking
DESCRIPTION=Escáner de redes y auditoría de puertos
HOMEPAGE=https://nmap.org/
LICENSE=Custom (Nmap Public Source License)
INSTALL_METHOD=brew
PACKAGE_NAME=nmap
PACKAGE_TYPE=formula
ARCHITECTURE=universal
