APP_ID=proton-pass
NAME=Proton Pass
CATEGORY=security
DESCRIPTION=Gestor de contraseñas de Proton con alias de correo integrados
HOMEPAGE=https://proton.me/pass
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=proton-pass
PACKAGE_TYPE=cask
ARCHITECTURE=universal
ALTERNATIVES=1Password, Bitwarden
