APP_ID=chatgpt
NAME=ChatGPT
CATEGORY=ai
DESCRIPTION=Cliente oficial de ChatGPT para macOS
HOMEPAGE=https://chatgpt.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=chatgpt
PACKAGE_TYPE=cask
ARCHITECTURE=universal
