APP_ID=librewolf
NAME=LibreWolf
CATEGORY=browsers
DESCRIPTION=Fork de Firefox endurecido en privacidad, sin telemetría
HOMEPAGE=https://librewolf.net/
LICENSE=MPL-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=librewolf
PACKAGE_TYPE=cask
ARCHITECTURE=universal
