APP_ID=tunnelblick
NAME=Tunnelblick
CATEGORY=security
DESCRIPTION=Cliente gráfico gratuito para OpenVPN
HOMEPAGE=https://tunnelblick.net/
LICENSE=GPL-2.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=tunnelblick
PACKAGE_TYPE=cask
ARCHITECTURE=universal
