APP_ID=microsoft-outlook
NAME=Microsoft Outlook
CATEGORY=productivity
DESCRIPTION=Cliente de correo electrónico y calendario de Microsoft 365
HOMEPAGE=https://www.microsoft.com/en-us/microsoft-365/outlook/outlook-for-business
LICENSE=Proprietary
INSTALL_METHOD=cask
PACKAGE_NAME=microsoft-outlook
PACKAGE_TYPE=cask
ARCHITECTURE=universal
