APP_ID=openmtp
NAME=OpenMTP
CATEGORY=device-management
DESCRIPTION=Transferencia de archivos Android para macOS
HOMEPAGE=https://openmtp.ganeshrvel.com/
LICENSE=MIT
INSTALL_METHOD=cask
PACKAGE_NAME=openmtp
PACKAGE_TYPE=cask
ARCHITECTURE=universal
NOTES=Alternativa moderna y más activa que Android File Transfer, la herramienta oficial de Google
