APP_ID=brave
NAME=Brave
CATEGORY=browsers
DESCRIPTION=Navegador basado en Chromium con bloqueo de anuncios y rastreadores integrado
HOMEPAGE=https://brave.com/
LICENSE=MPL-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=brave-browser
PACKAGE_TYPE=cask
ARCHITECTURE=universal
