APP_ID=perplexity
NAME=Perplexity
CATEGORY=ai
DESCRIPTION=Motor de búsqueda conversacional con respuestas basadas en IA
HOMEPAGE=https://www.perplexity.ai/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=perplexity
PACKAGE_TYPE=cask
ARCHITECTURE=universal
