APP_ID=pages
NAME=Pages
CATEGORY=productivity
DESCRIPTION=Procesador de textos de la suite iWork de Apple
HOMEPAGE=https://www.apple.com/pages/
LICENSE=Free
INSTALL_METHOD=mas
PACKAGE_NAME=361309726
PACKAGE_TYPE=app-store
ARCHITECTURE=universal
