APP_ID=floorp
NAME=Floorp
CATEGORY=browsers
DESCRIPTION=Navegador basado en Firefox enfocado en privacidad y personalización
HOMEPAGE=https://floorp.app/
LICENSE=MPL-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=floorp
PACKAGE_TYPE=cask
ARCHITECTURE=universal
