APP_ID=loop
NAME=Loop
CATEGORY=system
DESCRIPTION=Gestor de ventanas con menú radial
HOMEPAGE=https://github.com/MrKai77/Loop
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=loop
PACKAGE_TYPE=cask
ARCHITECTURE=universal
NOTES=Alternativa a Rectangle con un modelo de interacción distinto
