APP_ID=knockknock
NAME=KnockKnock
CATEGORY=security
DESCRIPTION=Revela qué software se ejecuta automáticamente al iniciar sesión
HOMEPAGE=https://objective-see.org/products/knockknock.html
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=knockknock
PACKAGE_TYPE=cask
ARCHITECTURE=universal
