APP_ID=tableplus
NAME=TablePlus
CATEGORY=development
DESCRIPTION=Cliente de bases de datos nativo, rápido y multi-motor
HOMEPAGE=https://tableplus.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=tableplus
PACKAGE_TYPE=cask
ARCHITECTURE=universal
