APP_ID=parallels
NAME=Parallels Desktop
CATEGORY=development
DESCRIPTION=Software de virtualización para ejecutar Windows y otros sistemas en Mac
HOMEPAGE=https://www.parallels.com/products/desktop/
LICENSE=Proprietary
INSTALL_METHOD=cask
PACKAGE_NAME=parallels
PACKAGE_TYPE=cask
ARCHITECTURE=universal
