APP_ID=goodnotes
NAME=Goodnotes
CATEGORY=productivity
DESCRIPTION=Toma de notas manuscritas y anotación de PDF
HOMEPAGE=https://www.goodnotes.com/
LICENSE=Freemium
INSTALL_METHOD=mas
PACKAGE_NAME=1444383602
PACKAGE_TYPE=app-store
ARCHITECTURE=universal
