APP_ID=rustdesk
NAME=RustDesk
CATEGORY=networking
DESCRIPTION=Escritorio remoto open-source, alternativa a TeamViewer
HOMEPAGE=https://rustdesk.com/
LICENSE=AGPL-3.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=rustdesk
PACKAGE_TYPE=cask
ARCHITECTURE=universal
