APP_ID=the-unarchiver
NAME=The Unarchiver
CATEGORY=system
DESCRIPTION=Descompresor universal de archivos comprimidos
HOMEPAGE=https://theunarchiver.com/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=the-unarchiver
PACKAGE_TYPE=cask
ARCHITECTURE=universal
ALTERNATIVES=Keka
