APP_ID=docker
NAME=Docker Desktop
CATEGORY=development
DESCRIPTION=Contenedores para desarrollo local
HOMEPAGE=https://www.docker.com/products/docker-desktop
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=docker-desktop
PACKAGE_TYPE=cask
ARCHITECTURE=universal
MIN_MACOS=12
RELATED=visual-studio-code git postman node
