APP_ID=pycharm-ce
NAME=PyCharm Community Edition
CATEGORY=development
DESCRIPTION=IDE para desarrollo en Python (edición gratuita)
HOMEPAGE=https://www.jetbrains.com/pycharm/
LICENSE=Apache-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=pycharm-ce
PACKAGE_TYPE=cask
ARCHITECTURE=universal
