APP_ID=microsoft-powerpoint
NAME=Microsoft PowerPoint
CATEGORY=productivity
DESCRIPTION=Presentaciones de Microsoft Office
HOMEPAGE=https://www.microsoft.com/en-US/microsoft-365/powerpoint
LICENSE=Proprietary
INSTALL_METHOD=cask
PACKAGE_NAME=microsoft-powerpoint
PACKAGE_TYPE=cask
ARCHITECTURE=universal
