APP_ID=inkscape
NAME=Inkscape
CATEGORY=creative
DESCRIPTION=Editor de gráficos vectoriales de código abierto
HOMEPAGE=https://inkscape.org/
LICENSE=GPL-3.0-or-later
INSTALL_METHOD=cask
PACKAGE_NAME=inkscape
PACKAGE_TYPE=cask
ARCHITECTURE=universal
