APP_ID=bitwarden
NAME=Bitwarden
CATEGORY=security
DESCRIPTION=Gestor de contraseñas open-source con opción de auto-alojamiento
HOMEPAGE=https://bitwarden.com/
LICENSE=GPL-3.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=bitwarden
PACKAGE_TYPE=cask
ARCHITECTURE=universal
ALTERNATIVES=1Password, Proton Pass
