APP_ID=kdenlive
NAME=Kdenlive
CATEGORY=creative
DESCRIPTION=Editor de video open-source
HOMEPAGE=https://kdenlive.org/
LICENSE=GPL-3.0-or-later
INSTALL_METHOD=cask
PACKAGE_NAME=kdenlive
PACKAGE_TYPE=cask
ARCHITECTURE=universal
