APP_ID=virtualbox
NAME=Oracle VirtualBox
CATEGORY=development
DESCRIPTION=Software de virtualización multiplataforma
HOMEPAGE=https://www.virtualbox.org/
LICENSE=GPL-2.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=virtualbox
PACKAGE_TYPE=cask
ARCHITECTURE=universal
