APP_ID=google-chrome
NAME=Google Chrome
CATEGORY=browsers
DESCRIPTION=Navegador de Google con el mayor soporte de extensiones del mercado
HOMEPAGE=https://www.google.com/chrome/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=google-chrome
PACKAGE_TYPE=cask
ARCHITECTURE=universal
