APP_ID=aldente
NAME=AlDente
CATEGORY=system
DESCRIPTION=Límite de carga de batería para prolongar su vida útil
HOMEPAGE=https://apphousekitchen.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=aldente
PACKAGE_TYPE=cask
ARCHITECTURE=universal
HW_RECOMMEND=macbook_air macbook_pro
