APP_ID=grammarly
NAME=Grammarly Desktop
CATEGORY=productivity
DESCRIPTION=Asistente de escritura y corrección gramatical con IA
HOMEPAGE=https://www.grammarly.com/desktop
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=grammarly-desktop
PACKAGE_TYPE=cask
ARCHITECTURE=universal
