APP_ID=spotify
NAME=Spotify
CATEGORY=media
DESCRIPTION=Streaming de música y podcasts
HOMEPAGE=https://www.spotify.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=spotify
PACKAGE_TYPE=cask
ARCHITECTURE=universal
