APP_ID=audacity
NAME=Audacity
CATEGORY=creative
DESCRIPTION=Editor y grabador de audio multipista
HOMEPAGE=https://www.audacityteam.org/
LICENSE=GPL-2.0-or-later
INSTALL_METHOD=cask
PACKAGE_NAME=audacity
PACKAGE_TYPE=cask
ARCHITECTURE=universal
