APP_ID=dropbox
NAME=Dropbox
CATEGORY=cloud
DESCRIPTION=Cliente del servicio de almacenamiento en la nube Dropbox
HOMEPAGE=https://www.dropbox.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=dropbox
PACKAGE_TYPE=cask
ARCHITECTURE=universal
