APP_ID=musicbrainz-picard
NAME=MusicBrainz Picard
CATEGORY=media
DESCRIPTION=Etiquetador de música basado en la base de datos MusicBrainz
HOMEPAGE=https://picard.musicbrainz.org/
LICENSE=GPL-2.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=musicbrainz-picard
PACKAGE_TYPE=cask
ARCHITECTURE=universal
