APP_ID=gitkraken
NAME=GitKraken
CATEGORY=development
DESCRIPTION=Cliente gráfico de Git enfocado en productividad
HOMEPAGE=https://www.gitkraken.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=gitkraken
PACKAGE_TYPE=cask
ARCHITECTURE=universal
