APP_ID=balenaetcher
NAME=balenaEtcher
CATEGORY=device-management
DESCRIPTION=Grabado de imágenes de sistema en tarjetas SD y USB
HOMEPAGE=https://etcher.balena.io/
LICENSE=Apache-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=balenaetcher
PACKAGE_TYPE=cask
ARCHITECTURE=universal
