APP_ID=iina
NAME=IINA
CATEGORY=media
DESCRIPTION=Reproductor de video moderno y nativo para macOS
HOMEPAGE=https://iina.io/
LICENSE=GPL-3.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=iina
PACKAGE_TYPE=cask
ARCHITECTURE=universal
