APP_ID=sourcetree
NAME=Sourcetree
CATEGORY=development
DESCRIPTION=Cliente gráfico gratuito de Atlassian para Git
HOMEPAGE=https://www.sourcetreeapp.com/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=sourcetree
PACKAGE_TYPE=cask
ARCHITECTURE=universal
