APP_ID=twingate
NAME=Twingate
CATEGORY=networking
DESCRIPTION=Acceso remoto seguro de confianza cero a redes privadas
HOMEPAGE=https://twingate.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=twingate
PACKAGE_TYPE=cask
ARCHITECTURE=universal
