APP_ID=gimp
NAME=GIMP
CATEGORY=creative
DESCRIPTION=Edición de imágenes open-source
HOMEPAGE=https://www.gimp.org/
LICENSE=GPL-3.0-or-later
INSTALL_METHOD=cask
PACKAGE_NAME=gimp
PACKAGE_TYPE=cask
ARCHITECTURE=universal
