APP_ID=makemkv
NAME=MakeMKV
CATEGORY=media
DESCRIPTION=Convierte y extrae video desde discos ópticos al formato MKV
HOMEPAGE=https://www.makemkv.com/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=makemkv
PACKAGE_TYPE=cask
ARCHITECTURE=universal
