APP_ID=scroll-reverser
NAME=Scroll Reverser
CATEGORY=system
DESCRIPTION=Invierte la dirección del desplazamiento del ratón o trackpad
HOMEPAGE=https://pilotmoon.com/scrollreverser/
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=scroll-reverser
PACKAGE_TYPE=cask
ARCHITECTURE=universal
