ID=keka
NAME=Keka
CASK=keka
DESCRIPTION=Compresor y descompresor moderno y sin publicidad
CATEGORIES=utilities
JB_PICK=true
JB_PICK_NOTE=Reemplazo moderno de The Unarchiver. Años de uso sin incidencias en equipos de clientes.
RECOMMENDED=true
