ID=keka
NAME=Keka
INSTALL_METHOD=cask
PACKAGE=keka
DESCRIPTION=Compresor y descompresor moderno y sin publicidad
CATEGORY=utilities
JB_PICK=true
JB_PICK_NOTE=Reemplazo moderno de The Unarchiver. Años de uso sin incidencias en equipos de clientes.
