APP_ID=apple-configurator
NAME=Apple Configurator
CATEGORY=device-management
DESCRIPTION=Configuración, supervisión e implementación masiva de dispositivos Apple
HOMEPAGE=https://apps.apple.com/app/apple-configurator/id1037126344
LICENSE=Free
INSTALL_METHOD=mas
PACKAGE_NAME=1037126344
PACKAGE_TYPE=app-store
ARCHITECTURE=universal
