APP_ID=keepassxc
NAME=KeePassXC
CATEGORY=security
DESCRIPTION=Gestor de contraseñas multiplataforma y de código abierto
HOMEPAGE=https://keepassxc.org/
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=keepassxc
PACKAGE_TYPE=cask
ARCHITECTURE=universal
