APP_ID=angry-ip-scanner
NAME=Angry IP Scanner
CATEGORY=networking
DESCRIPTION=Escáner rápido de direcciones IP en red local
HOMEPAGE=https://angryip.org/
LICENSE=GPL-2.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=angry-ip-scanner
PACKAGE_TYPE=cask
ARCHITECTURE=universal
