APP_ID=adobe-acrobat-reader
NAME=Adobe Acrobat Reader
CATEGORY=productivity
DESCRIPTION=Lector de PDF estándar de la industria, con firma y comentarios
HOMEPAGE=https://www.adobe.com/acrobat/pdf-reader.html
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=adobe-acrobat-reader
PACKAGE_TYPE=cask
ARCHITECTURE=universal
