APP_ID=keynote
NAME=Keynote
CATEGORY=productivity
DESCRIPTION=Presentaciones de la suite iWork de Apple
HOMEPAGE=https://www.apple.com/keynote/
LICENSE=Free
INSTALL_METHOD=mas
PACKAGE_NAME=361285480
PACKAGE_TYPE=app-store
ARCHITECTURE=universal
