APP_ID=android-studio
NAME=Android Studio
CATEGORY=development
DESCRIPTION=IDE oficial de Google para desarrollo de apps Android
HOMEPAGE=https://developer.android.com/studio/
LICENSE=Apache-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=android-studio
PACKAGE_TYPE=cask
ARCHITECTURE=universal
