APP_ID=mac-mouse-fix
NAME=Mac Mouse Fix
CATEGORY=system
DESCRIPTION=Personalización de botones y gestos para mouse en macOS
HOMEPAGE=https://macmousefix.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=mac-mouse-fix
PACKAGE_TYPE=cask
ARCHITECTURE=universal
