APP_ID=raycast
NAME=Raycast
CATEGORY=system
DESCRIPTION=Lanzador de aplicaciones y productividad mediante atajos de teclado
HOMEPAGE=https://raycast.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=raycast
PACKAGE_TYPE=cask
ARCHITECTURE=universal
