APP_ID=steam
NAME=Steam
CATEGORY=media
DESCRIPTION=Plataforma de distribución y biblioteca de videojuegos
HOMEPAGE=https://store.steampowered.com/about/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=steam
PACKAGE_TYPE=cask
ARCHITECTURE=universal
