APP_ID=whatsapp
NAME=WhatsApp
CATEGORY=communication
DESCRIPTION=Cliente de escritorio oficial de WhatsApp
HOMEPAGE=https://www.whatsapp.com/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=whatsapp
PACKAGE_TYPE=cask
ARCHITECTURE=universal
