APP_ID=bettertouchtool
NAME=BetterTouchTool
CATEGORY=system
DESCRIPTION=Personaliza gestos, atajos y automatizaciones del sistema
HOMEPAGE=https://folivora.ai/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=bettertouchtool
PACKAGE_TYPE=cask
ARCHITECTURE=universal
