APP_ID=krita
NAME=Krita
CATEGORY=creative
DESCRIPTION=Programa de pintura digital y dibujo de código abierto
HOMEPAGE=https://krita.org/
LICENSE=GPL-3.0-or-later
INSTALL_METHOD=cask
PACKAGE_NAME=krita
PACKAGE_TYPE=cask
ARCHITECTURE=universal
