APP_ID=sublime-text
NAME=Sublime Text
CATEGORY=development
DESCRIPTION=Editor de texto rápido para código, marcado y prosa
HOMEPAGE=https://www.sublimetext.com/
LICENSE=Paid
INSTALL_METHOD=cask
PACKAGE_NAME=sublime-text
PACKAGE_TYPE=cask
ARCHITECTURE=universal
