APP_ID=rocket
NAME=Rocket
CATEGORY=system
DESCRIPTION=Selector de emojis para la barra de menús
HOMEPAGE=https://matthewpalmer.net/rocket/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=rocket
PACKAGE_TYPE=cask
ARCHITECTURE=universal
