APP_ID=tailscale
NAME=Tailscale
CATEGORY=networking
DESCRIPTION=Red privada mesh basada en WireGuard
HOMEPAGE=https://tailscale.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=tailscale-app
PACKAGE_TYPE=cask
ARCHITECTURE=universal
