APP_ID=postman
NAME=Postman
CATEGORY=development
DESCRIPTION=Cliente y colecciones para probar y documentar APIs
HOMEPAGE=https://www.postman.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=postman
PACKAGE_TYPE=cask
ARCHITECTURE=universal
RELATED=docker visual-studio-code node
