APP_ID=clamxav
NAME=ClamXAV
CATEGORY=security
DESCRIPTION=Antivirus y escáner de malware basado en ClamAV
HOMEPAGE=https://www.clamxav.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=clamxav
PACKAGE_TYPE=cask
ARCHITECTURE=universal
