APP_ID=onyx
NAME=OnyX
CATEGORY=system
DESCRIPTION=Verificación de estructuras del sistema y tareas de mantenimiento
HOMEPAGE=https://www.titanium-software.fr/en/onyx.html
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=onyx
PACKAGE_TYPE=cask
ARCHITECTURE=universal
REQUIREMENTS=Existe una versión específica de OnyX por cada versión mayor de macOS; verificar compatibilidad antes de instalar.
