APP_ID=jellyfin
NAME=Jellyfin Media Player
CATEGORY=media
DESCRIPTION=Cliente del servidor multimedia autoalojado Jellyfin
HOMEPAGE=https://jellyfin.org/
LICENSE=GPL-2.0-or-later
INSTALL_METHOD=cask
PACKAGE_NAME=jellyfin-media-player
PACKAGE_TYPE=cask
ARCHITECTURE=universal
