APP_ID=betterdisplay
NAME=BetterDisplay
CATEGORY=system
DESCRIPTION=Gestión avanzada de pantallas, resoluciones y brillo
HOMEPAGE=https://betterdisplay.pro/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=betterdisplay
PACKAGE_TYPE=cask
ARCHITECTURE=universal
HW_RECOMMEND=mac_mini mac_studio external_display
