APP_ID=ticktick
NAME=TickTick
CATEGORY=productivity
DESCRIPTION=Gestión de tareas y hábitos con calendario integrado
HOMEPAGE=https://www.ticktick.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=ticktick
PACKAGE_TYPE=cask
ARCHITECTURE=universal
