APP_ID=handbrake
NAME=HandBrake
CATEGORY=media
DESCRIPTION=Conversión de video a formatos modernos con perfiles predefinidos
HOMEPAGE=https://handbrake.fr/
LICENSE=GPL-2.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=handbrake
PACKAGE_TYPE=cask
ARCHITECTURE=universal
