APP_ID=chromium
NAME=Chromium
CATEGORY=browsers
DESCRIPTION=Base open-source del proyecto Chrome, sin telemetría de Google
HOMEPAGE=https://www.chromium.org/Home
LICENSE=BSD-3-Clause
INSTALL_METHOD=cask
PACKAGE_NAME=chromium
PACKAGE_TYPE=cask
ARCHITECTURE=universal
