APP_ID=insomnia
NAME=Insomnia
CATEGORY=development
DESCRIPTION=Cliente HTTP y GraphQL para probar y depurar APIs
HOMEPAGE=https://insomnia.rest/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=insomnia
PACKAGE_TYPE=cask
ARCHITECTURE=universal
NOTES=Alternativa más ligera y open-core a Postman
