APP_ID=mas
NAME=mas
CATEGORY=system
DESCRIPTION=Cliente de línea de comandos para la Mac App Store
HOMEPAGE=https://github.com/mas-cli/mas
LICENSE=MIT
INSTALL_METHOD=brew
PACKAGE_NAME=mas
PACKAGE_TYPE=formula
ARCHITECTURE=universal
