APP_ID=facebook-messenger
NAME=Facebook Messenger
CATEGORY=communication
DESCRIPTION=Cliente de escritorio oficial de Messenger
HOMEPAGE=https://www.messenger.com/desktop
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=messenger
PACKAGE_TYPE=cask
ARCHITECTURE=universal
