APP_ID=oversight
NAME=OverSight
CATEGORY=security
DESCRIPTION=Alerta cuando la cámara o el micrófono se activan
HOMEPAGE=https://objective-see.org/products/oversight.html
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=oversight
PACKAGE_TYPE=cask
ARCHITECTURE=universal
