APP_ID=visual-studio-code
NAME=Visual Studio Code
CATEGORY=development
DESCRIPTION=Editor de código extensible
HOMEPAGE=https://code.visualstudio.com/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=visual-studio-code
PACKAGE_TYPE=cask
ARCHITECTURE=universal
RELATED=docker git node
