APP_ID=wireguard
NAME=WireGuard
CATEGORY=security
DESCRIPTION=VPN moderna, simple y de alto rendimiento
HOMEPAGE=https://www.wireguard.com/
LICENSE=GPL-2.0-only
INSTALL_METHOD=mas
PACKAGE_NAME=1451685025
PACKAGE_TYPE=app-store
ARCHITECTURE=universal
