APP_ID=monitorcontrol
NAME=MonitorControl
CATEGORY=system
DESCRIPTION=Controla brillo y volumen de monitores externos desde el Mac
HOMEPAGE=https://github.com/MonitorControl/MonitorControl
LICENSE=MIT
INSTALL_METHOD=cask
PACKAGE_NAME=monitorcontrol
PACKAGE_TYPE=cask
ARCHITECTURE=universal
ALTERNATIVES=BetterDisplay
