APP_ID=gpg-suite
NAME=GPG Suite
CATEGORY=security
DESCRIPTION=Herramientas para cifrar correos y archivos con GPG
HOMEPAGE=https://gpgtools.org/
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=gpg-suite
PACKAGE_TYPE=cask
ARCHITECTURE=universal
