APP_ID=resilio-sync
NAME=Resilio Sync
CATEGORY=cloud
DESCRIPTION=Sincronización de archivos peer-to-peer sin servidor central
HOMEPAGE=https://www.resilio.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=resilio-sync
PACKAGE_TYPE=cask
ARCHITECTURE=universal
