APP_ID=libreoffice
NAME=LibreOffice
CATEGORY=productivity
DESCRIPTION=Suite ofimática open-source compatible con formatos de Microsoft Office
HOMEPAGE=https://www.libreoffice.org/
LICENSE=MPL-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=libreoffice
PACKAGE_TYPE=cask
ARCHITECTURE=universal
