APP_ID=numbers
NAME=Numbers
CATEGORY=productivity
DESCRIPTION=Hojas de cálculo de la suite iWork de Apple
HOMEPAGE=https://www.apple.com/numbers/
LICENSE=Free
INSTALL_METHOD=mas
PACKAGE_NAME=361304891
PACKAGE_TYPE=app-store
ARCHITECTURE=universal
