APP_ID=hazeover
NAME=HazeOver
CATEGORY=system
DESCRIPTION=Atenúa ventanas inactivas para reducir distracciones
HOMEPAGE=https://hazeover.com/
LICENSE=Paid
INSTALL_METHOD=cask
PACKAGE_NAME=hazeover
PACKAGE_TYPE=cask
ARCHITECTURE=universal
