APP_ID=ffmpeg
NAME=FFmpeg
CATEGORY=media
DESCRIPTION=Conversión y procesamiento de audio y video desde línea de comandos
HOMEPAGE=https://ffmpeg.org/
LICENSE=GPL-3.0-or-later
INSTALL_METHOD=brew
PACKAGE_NAME=ffmpeg
PACKAGE_TYPE=formula
ARCHITECTURE=universal
