APP_ID=google-drive
NAME=Google Drive
CATEGORY=cloud
DESCRIPTION=Cliente del servicio de almacenamiento en la nube de Google
HOMEPAGE=https://www.google.com/drive/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=google-drive
PACKAGE_TYPE=cask
ARCHITECTURE=universal
