APP_ID=hex-fiend
NAME=Hex Fiend
CATEGORY=system
DESCRIPTION=Editor hexadecimal rápido para archivos grandes
HOMEPAGE=https://hexfiend.com/
LICENSE=BSD-2-Clause
INSTALL_METHOD=cask
PACKAGE_NAME=hex-fiend
PACKAGE_TYPE=cask
ARCHITECTURE=universal
