APP_ID=maccy
NAME=Maccy
CATEGORY=system
DESCRIPTION=Gestor de historial del portapapeles
HOMEPAGE=https://maccy.app/
LICENSE=MIT
INSTALL_METHOD=cask
PACKAGE_NAME=maccy
PACKAGE_TYPE=cask
ARCHITECTURE=universal
