APP_ID=ollama
NAME=Ollama
CATEGORY=ai
DESCRIPTION=Ejecuta y gestiona modelos de lenguaje open-source localmente
HOMEPAGE=https://ollama.com/
LICENSE=MIT
INSTALL_METHOD=cask
PACKAGE_NAME=ollama
PACKAGE_TYPE=cask
ARCHITECTURE=universal
RELATED=anythingllm lm-studio gpt4all chatgpt
