APP_ID=itsycal
NAME=Itsycal
CATEGORY=system
DESCRIPTION=Calendario compacto en la barra de menús
HOMEPAGE=https://www.mowglii.com/itsycal/
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=itsycal
PACKAGE_TYPE=cask
ARCHITECTURE=universal
