APP_ID=mysql-workbench
NAME=MySQL Workbench
CATEGORY=development
DESCRIPTION=Diseño, administración y consultas visuales para MySQL
HOMEPAGE=https://www.mysql.com/products/workbench/
LICENSE=GPL-2.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=mysqlworkbench
PACKAGE_TYPE=cask
ARCHITECTURE=universal
