APP_ID=zerotier
NAME=ZeroTier One
CATEGORY=networking
DESCRIPTION=Red privada virtual de malla, alternativa a Tailscale
HOMEPAGE=https://www.zerotier.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=zerotier-one
PACKAGE_TYPE=cask
ARCHITECTURE=universal
