APP_ID=microsoft-remote-desktop
NAME=Microsoft Remote Desktop
CATEGORY=networking
DESCRIPTION=Cliente oficial de Microsoft para conexiones de escritorio remoto RDP
HOMEPAGE=https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=microsoft-remote-desktop
PACKAGE_TYPE=cask
ARCHITECTURE=universal
