APP_ID=slack
NAME=Slack
CATEGORY=communication
DESCRIPTION=Mensajería y colaboración por canales para equipos
HOMEPAGE=https://slack.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=slack
PACKAGE_TYPE=cask
ARCHITECTURE=universal
