APP_ID=obs-studio
NAME=OBS Studio
CATEGORY=creative
DESCRIPTION=Grabación y transmisión en vivo open-source
HOMEPAGE=https://obsproject.com/
LICENSE=GPL-2.0-or-later
INSTALL_METHOD=cask
PACKAGE_NAME=obs
PACKAGE_TYPE=cask
ARCHITECTURE=universal
