APP_ID=imazing
NAME=iMazing
CATEGORY=device-management
DESCRIPTION=Gestión avanzada de dispositivos iPhone y iPad
HOMEPAGE=https://imazing.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=imazing
PACKAGE_TYPE=cask
ARCHITECTURE=universal
