APP_ID=notion
NAME=Notion
CATEGORY=productivity
DESCRIPTION=Notas, documentos y bases de datos en un solo espacio de trabajo
HOMEPAGE=https://www.notion.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=notion
PACKAGE_TYPE=cask
ARCHITECTURE=universal
