APP_ID=mullvad-vpn
NAME=Mullvad VPN
CATEGORY=security
DESCRIPTION=VPN enfocada en privacidad, sin registro de cuenta con email
HOMEPAGE=https://mullvad.net/
LICENSE=Paid
INSTALL_METHOD=cask
PACKAGE_NAME=mullvadvpn
PACKAGE_TYPE=cask
ARCHITECTURE=universal
ALTERNATIVES=Proton VPN, Tunnelblick
