APP_ID=plex
NAME=Plex
CATEGORY=media
DESCRIPTION=Cliente para el servidor multimedia personal Plex
HOMEPAGE=https://www.plex.tv/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=plex
PACKAGE_TYPE=cask
ARCHITECTURE=universal
