APP_ID=shotcut
NAME=Shotcut
CATEGORY=creative
DESCRIPTION=Editor de video no lineal de código abierto
HOMEPAGE=https://www.shotcut.org/
LICENSE=GPL-3.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=shotcut
PACKAGE_TYPE=cask
ARCHITECTURE=universal
