APP_ID=spark-mail
NAME=Spark
CATEGORY=communication
DESCRIPTION=Cliente de correo de Readdle con bandeja inteligente y colaboración
HOMEPAGE=https://sparkmailapp.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=readdle-spark
PACKAGE_TYPE=cask
ARCHITECTURE=universal
