APP_ID=losslesscut
NAME=LosslessCut
CATEGORY=creative
DESCRIPTION=Recorta video y audio sin pérdida de calidad ni recodificación
HOMEPAGE=https://github.com/mifi/lossless-cut
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=losslesscut
PACKAGE_TYPE=cask
ARCHITECTURE=universal
