APP_ID=kodi
NAME=Kodi
CATEGORY=media
DESCRIPTION=Centro multimedia gratuito y de código abierto
HOMEPAGE=https://kodi.tv/
LICENSE=GPL-2.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=kodi
PACKAGE_TYPE=cask
ARCHITECTURE=universal
