APP_ID=termius
NAME=Termius
CATEGORY=networking
DESCRIPTION=Cliente SSH multiplataforma con sincronización de sesiones
HOMEPAGE=https://www.termius.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=termius
PACKAGE_TYPE=cask
ARCHITECTURE=universal
