APP_ID=android-platform-tools
NAME=Android Platform Tools
CATEGORY=device-management
DESCRIPTION=Herramientas adb y fastboot para dispositivos Android
HOMEPAGE=https://developer.android.com/tools/releases/platform-tools
LICENSE=Apache-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=android-platform-tools
PACKAGE_TYPE=cask
ARCHITECTURE=universal
