APP_ID=android-file-transfer
NAME=Android File Transfer
CATEGORY=device-management
DESCRIPTION=Herramienta oficial de Google para transferir archivos desde y hacia Android
HOMEPAGE=https://www.android.com/filetransfer/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=android-file-transfer
PACKAGE_TYPE=cask
ARCHITECTURE=universal
