APP_ID=logi-options-plus
NAME=Logi Options+
CATEGORY=system
DESCRIPTION=Configuración oficial de mouse y teclado Logitech
HOMEPAGE=https://www.logitech.com/en-us/software/logi-options-plus.html
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=logi-options+
PACKAGE_TYPE=cask
ARCHITECTURE=universal
ALTERNATIVES=OpenLogi
