APP_ID=intellij-idea-ce
NAME=IntelliJ IDEA Community Edition
CATEGORY=development
DESCRIPTION=IDE para desarrollo en Java (edición gratuita)
HOMEPAGE=https://www.jetbrains.com/idea/
LICENSE=Apache-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=intellij-idea-ce
PACKAGE_TYPE=cask
ARCHITECTURE=universal
