APP_ID=blender
NAME=Blender
CATEGORY=creative
DESCRIPTION=Suite de creación 3D gratuita y de código abierto
HOMEPAGE=https://www.blender.org/
LICENSE=GPL-2.0-or-later
INSTALL_METHOD=cask
PACKAGE_NAME=blender
PACKAGE_TYPE=cask
ARCHITECTURE=universal
