APP_ID=firefox
NAME=Firefox
CATEGORY=browsers
DESCRIPTION=Navegador independiente de Mozilla enfocado en privacidad
HOMEPAGE=https://www.mozilla.org/firefox/
LICENSE=MPL-2.0
INSTALL_METHOD=cask
PACKAGE_NAME=firefox
PACKAGE_TYPE=cask
ARCHITECTURE=universal
