APP_ID=openvpn-connect
NAME=OpenVPN Connect
CATEGORY=security
DESCRIPTION=Cliente oficial para conectarse a servidores OpenVPN Access Server
HOMEPAGE=https://openvpn.net/client-connect-vpn-for-mac-os/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=openvpn-connect
PACKAGE_TYPE=cask
ARCHITECTURE=universal
