APP_ID=jan
NAME=Jan
CATEGORY=ai
DESCRIPTION=Asistente de IA que se ejecuta completamente offline en el equipo
HOMEPAGE=https://jan.ai/
LICENSE=AGPL-3.0-only
INSTALL_METHOD=cask
PACKAGE_NAME=jan
PACKAGE_TYPE=cask
ARCHITECTURE=universal
