APP_ID=hiddenbar
NAME=Hidden Bar
CATEGORY=system
DESCRIPTION=Oculta iconos de la barra de menús para reducir el desorden
HOMEPAGE=https://github.com/dwarvesf/hidden/
LICENSE=MIT
INSTALL_METHOD=cask
PACKAGE_NAME=hiddenbar
PACKAGE_TYPE=cask
ARCHITECTURE=universal
