APP_ID=zed
NAME=Zed
CATEGORY=development
DESCRIPTION=Editor de código multijugador de alto rendimiento
HOMEPAGE=https://zed.dev/
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=zed
PACKAGE_TYPE=cask
ARCHITECTURE=universal
