APP_ID=git
NAME=Git
CATEGORY=development
DESCRIPTION=Control de versiones distribuido
HOMEPAGE=https://git-scm.com
LICENSE=GPL-2.0-only
INSTALL_METHOD=brew
PACKAGE_NAME=git
PACKAGE_TYPE=formula
ARCHITECTURE=universal
RELATED=visual-studio-code docker
