APP_ID=github
NAME=GitHub Desktop
CATEGORY=development
DESCRIPTION=Cliente gráfico oficial de GitHub para gestionar repositorios Git
HOMEPAGE=https://desktop.github.com/
LICENSE=MIT
INSTALL_METHOD=cask
PACKAGE_NAME=github
PACKAGE_TYPE=cask
ARCHITECTURE=universal
