APP_ID=megasync
NAME=MEGAsync
CATEGORY=cloud
DESCRIPTION=Sincronización con almacenamiento en la nube cifrado de MEGA
HOMEPAGE=https://mega.nz/sync
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=megasync
PACKAGE_TYPE=cask
ARCHITECTURE=universal
