APP_ID=todoist
NAME=Todoist
CATEGORY=productivity
DESCRIPTION=Gestión de tareas y proyectos personales
HOMEPAGE=https://todoist.com/home
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=todoist
PACKAGE_TYPE=cask
ARCHITECTURE=universal
