APP_ID=ngrok
NAME=ngrok
CATEGORY=networking
DESCRIPTION=Proxy inverso para exponer servicios locales de forma segura
HOMEPAGE=https://ngrok.com/
LICENSE=Freemium
INSTALL_METHOD=cask
PACKAGE_NAME=ngrok
PACKAGE_TYPE=cask
ARCHITECTURE=universal
