APP_ID=sonos
NAME=Sonos S2
CATEGORY=media
DESCRIPTION=Control de altavoces y sistemas de audio Sonos
HOMEPAGE=https://www.sonos.com/
LICENSE=Free
INSTALL_METHOD=cask
PACKAGE_NAME=sonos
PACKAGE_TYPE=cask
ARCHITECTURE=universal
