APP_ID=nextcloud
NAME=Nextcloud
CATEGORY=cloud
DESCRIPTION=Cliente de sincronización para servidores Nextcloud autoalojados
HOMEPAGE=https://nextcloud.com/
LICENSE=Open Source
INSTALL_METHOD=cask
PACKAGE_NAME=nextcloud
PACKAGE_TYPE=cask
ARCHITECTURE=universal
NOTES=Especialmente relevante para negocios que alojan su propio servidor de archivos
